name: Deploy Better-Starboard to Server

on: 
  push:
    branches:
      - main

env:
  FILENAME: better-starboard

jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set dotenv vars
      run: echo "BS_TOKEN=${{ secrets.BS_TOKEN }}" >> .env

    - name: Copy project via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "./"
        target: "~/programs/${{ env.FILENAME }}"

    - name: Stop and Restart application on host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          pkill -9 -f ${{ env.FILENAME }}.py
          cd ~/programs/${{ env.FILENAME }} && ~/programs/${{ env.FILENAME }}/venv/bin/python ${{ env.FILENAME }}.py > /tmp/cronlog.txt 2>&1