name: Deploy Better-Starboard - Reusable

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      FILENAME:
        required: true
        type: string
      DEST_DIR:
        required: true
        type: string
      VOLUME_NAME:
        required: true
        type: string
      RESTART_POLICY:
        required: true
        type: string

jobs:

  deploy:
    name: Copy, Build and Deploy Docker Container
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set dotenv vars
      run: echo "BS_TOKEN=${{ secrets.BS_TOKEN }}" >> ./src/.env

    - name: Copy Project to Host
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "./"
        target: "~/${{ inputs.DEST_DIR }}/${{ inputs.FILENAME }}"

    - name: Build and Redeploy Docker Container on Host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          docker build --tag ${{ inputs.FILENAME }} ~/${{ inputs.DEST_DIR }}/${{ inputs.FILENAME }}/.
          (docker stop ${{ inputs.FILENAME }} || true) && \
          (docker rm ${{ inputs.FILENAME }} || true) && \
          docker run -d \
            --restart=${{ inputs.RESTART_POLICY }} \
            --volume ${{ inputs.VOLUME_NAME }}:/bs \
            --name ${{ inputs.FILENAME }} ${{ inputs.FILENAME }}:latest
        
        # docker volume inspect ${{ inputs.VOLUME_NAME }} || docker volume create ${{ inputs.VOLUME_NAME }}