name: Deploy Better-Starboard to Server

on: 
  push:
    branches:
      - dev
      - main
    paths:
      - src/**
      - Dockerfile

jobs:

  prod:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/deploy-reusable.yaml
    with:
      ENVIRONMENT: prod
      FILENAME: better-starboard
      DEST_DIR: programs 
    secrets: inherit
  
  dev:
    if: ${{ github.ref == 'refs/heads/dev' }}
    uses: ./.github/workflows/deploy-reusable.yaml
    with:
      ENVIRONMENT: dev
      FILENAME: better-starboard-dev
      DEST_DIR: programs
    secrets: inherit